
GET http://localhost:6060/register

#####


POST http://localhost:6060/register HTTP/1.1
Content-Type: application/json

{
"name": "FirstName",
"surname": "LastName",
"email": "email@email.com",
"password": "Test1234"
}

#####

GET  http://localhost:7070/login

#####

POST http://localhost:6060/auth/login HTTP/1.1
Content-Type: application/json

{
"email": "prova@prova.com",
"password": "prova1234"
}

#####

POST http://localhost:7070/login HTTP/1.1
Content-Type: application/json

{
"email": "prova3@prova.it",
"password": "prova1234"
}

#####

GET http://localhost:6060/allproducts 

#####
POST http://localhost:7070/allproducts HTTP/1.1
Content-Type: application/json

{
"product": "prova2",
"thumbnail": "prova2",
"description": "prova2",
"category": "prova2",
"price": 5
}

#####

GET http://localhost:6060/auth/employess

#####

PATCH    http://localhost:7070/allproducts/642ff301e9528ead2de243d9 HTTP/1.1
Content-Type: application/json

{
"product": "OPPO Find N2 Flip",
"thumbnail": "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71p65d7yotL._AC_SL1500_.jpg",
"description": "OPPO Find N2 Flip è uno smartphone pieghevole lanciato da OPPO anche in Italia.",
"price": "1199,99",
"category": "Smartphone"
}

#####

DELETE http://localhost:7070/allproducts/642fe04a456fd63265297551d